export const PLANETS_REQUEST = 'PLANETS_REQUEST'
export const PLANETS_RESPONSE = 'PLANETS_RESPONSE'
export const PLANETS_RESPONSE_FAIL = 'PLANETS_RESPONSE_FAIL'

export const CHARACTERS_REQUEST = 'CHARACTERS_REQUEST'
export const CHARACTERS_RESPONSE = 'CHARACTERS_RESPONSE'
export const CHARACTERS_RESPONSE_FAIL = 'CHARACTERS_RESPONSE_FAIL'

export const STARSHIPS_REQUEST = 'STARSHIPS_REQUEST'
export const STARSHIPS_RESPONSE = 'STARSHIPS_RESPONSE'
export const STARSHIPS_RESPONSE_FAIL = 'STARSHIPS_RESPONSE_FAIL'

export const FILMS_REQUEST = 'FILMS_REQUEST'
export const FILMS_RESPONSE = 'FILMS_RESPONSE'
export const FILMS_RESPONSE_FAIL = 'FILMS_RESPONSE_FAIL'
