export const PLANETS_REQUEST = 'PLANETS_REQUEST'
export const PLANETS_RESPONSE = 'PLANETS_RESPONSE'
export const PLANETS_RESPONSE_FAIL = 'PLANETS_RESPONSE_FAIL'

export const PLANETS_DETAILS_REQUEST = 'PLANETS_DETAILS_REQUEST'
export const PLANETS_DETAILS_RESPONSE = 'PLANETS_DETAILS_RESPONSE'
export const PLANETS_DETAILS_RESPONSE_FAIL = 'PLANETS_DETAILS_RESPONSE_FAIL'

export const CHARACTERS_REQUEST = 'CHARACTERS_REQUEST'
export const CHARACTERS_RESPONSE = 'CHARACTERS_RESPONSE'
export const CHARACTERS_RESPONSE_FAIL = 'CHARACTERS_RESPONSE_FAIL'

export const CHARACTERS_DETAILS_REQUEST = 'CHARACTERS_DETAILS_REQUEST'
export const CHARACTERS_DETAILS_RESPONSE = 'CHARACTERS_DETAILS_RESPONSE'
export const CHARACTERS_DETAILS_RESPONSE_FAIL = 'CHARACTERS_DETAILS_RESPONSE_FAIL'

export const STARSHIPS_REQUEST = 'STARSHIPS_REQUEST'
export const STARSHIPS_RESPONSE = 'STARSHIPS_RESPONSE'
export const STARSHIPS_RESPONSE_FAIL = 'STARSHIPS_RESPONSE_FAIL'

export const STARSHIPS_DETAILS_REQUEST = 'STARSHIPS_DETAILS_REQUEST'
export const STARSHIPS_DETAILS_RESPONSE = 'STARSHIPS_DETAILS_RESPONSE'
export const STARSHIPS_DETAILS_RESPONSE_FAIL = 'STARSHIPS_DETAILS_RESPONSE_FAIL'

export const FILMS_REQUEST = 'FILMS_REQUEST'
export const FILMS_RESPONSE = 'FILMS_RESPONSE'
export const FILMS_RESPONSE_FAIL = 'FILMS_RESPONSE_FAIL'

export const FILMS_DETAILS_REQUEST = 'FILMS_DETAILS_REQUEST'
export const FILMS_DETAILS_RESPONSE = 'FILMS_DETAILS_RESPONSE'
export const FILMS_DETAILS_RESPONSE_FAIL = 'FILMS_DETAILS_RESPONSE_FAIL'

export const SET_THEME = 'SET_THEME'

export const USER_LOG_IN_REQUEST = 'USER_LOG_IN_REQUEST'
export const USER_SIGN_UP_REQUEST = 'USER_SIGN_UP_REQUEST'
export const USER_RESPONSE = 'USER_RESPONSE'
export const USER_RESPONSE_FAIL = 'USER_RESPONSE_FAIL'
export const REMOVE_USER = 'REMOVE_USER'
