export const PLANETS_REQUEST = 'PLANETS_REQUEST'
export const PLANETS_RESPONSE = 'PLANETS_RESPONSE'
export const PLANETS_RESPONSE_FAIL = 'PLANETS_RESPONSE_FAIL'

export const CHARACTERS_REQUEST = 'CHARACTERS_REQUEST'
export const CHARACTERS_RESPONSE = 'CHARACTERS_RESPONSE'
export const CHARACTERS_RESPONSE_FAIL = 'CHARACTERS_RESPONSE_FAIL'
