export const PLANETS_API_PATH = '/planets'
export const CHARACTERS_API_PATH = '/people'
export const STARSHIPS_API_PATH = '/starships'
export const FILMS_API_PATH = '/films'

export const ROOT_PATH = '/'
export const PLANETS_PAGE_PATH = '/planets'
export const CHARACTERS_PAGE_PATH = '/characters'
export const STARSHIPS_PAGE_PATH = '/starships'
export const FILMS_PAGE_PATH = '/films'
export const CARD_DETAILS_PAGE_PATH = '/card-details'
