export const PLANETS_API_PATH = '/planets'
export const CHARACTERS_API_PATH = '/people'
export const STARSHIPS_API_PATH = '/starships'
export const FILMS_API_PATH = '/films'

export const ROOT_PATH = '/'
export const PLANETS_PAGE_PATH = '/planets'
export const CHARACTERS_PAGE_PATH = '/characters'
export const STARSHIPS_PAGE_PATH = '/starships'
export const FILMS_PAGE_PATH = '/films'
export const CARD_DETAILS_PAGE_PATH = '/card-details'
export const LOGIN_PAGE_PATH = '/login'
export const REGISTER_PAGE_PATH = '/register'
export const NOT_FOUND_PATH = '/not-found'
export const NOT_AUTHORIZED_PATH = '/not-authorized'
