export default {
  common: {
    related_films: 'Related films:',
    residents: 'Residents:',
    starships: 'Starships:',
    pilots: 'Pilots:',
    characters: 'Characters:',
    planets: 'Planets:',
    credits: 'credits',
    km: 'km',
    m: 'm',
    kmH: 'km/h',
    days: 'days',
    kg: 'kg',
    cm: 'cm',
    search: 'Search...',
  },
  main: {
    welcome: 'Star Wars Application!',
    nameOfButton: 'Get Started',
  },
  header: {
    planets: 'planets',
    characters: 'characters',
    starships: 'starships',
    films: 'films',
  },
  planet: {
    population: 'Population',
    rotation_period: 'Rotation Period',
    orbital_period: 'Orbital Period',
    diameter: 'Diameter',
    gravity: 'Gravity',
    terrain: 'Terrain',
    surface_water: 'Surface Water',
    climate: 'Climate',
  },
  character: {
    birth_year: 'Birth year',
    height: 'Height',
    mass: 'Mass',
    gender: 'Gender',
    hair_color: 'Hair Color',
    skin_color: 'Fair',
    homeworld: 'Homeworld',
    species: 'Species',
  },
  starship: {
    model: 'Model',
    manufacturer: 'Manufacturer',
    class: 'Class',
    cost: 'Cost',
    speed: 'Speed',
    hyperdrive_rating: 'Hyperdrive Rating',
    MGLT: 'MGLT',
    length: 'Length',
    cargo_capacity: 'Cargo Capacity',
    minimum_сrew: 'Minimum Crew',
    passengers: 'Passengers',
  },
  film: {
    date_created: 'Date Created',
    director: 'Director',
    producer: 'Producer(s)',
    opening_crawl: 'Opening Crawl',
  },
}
