export default {
  common: {
    related_films: 'Фильмы:',
    residents: 'Жители:',
    characters: 'Персонажи:',
    starships: 'Звездолеты:',
    planets: 'Планеты:',
    pilots: 'Пилоты:',
    credits: 'кредитов',
    km: 'км',
    days: 'дней',
    kg: 'кг',
    cm: 'см',
    m: 'м',
    kmH: 'км/ч',
    search: 'Найти...',
    goBack: 'Вернуться',
  },
  main: {
    welcome: 'Приложение по Звездным Войнам!',
    get_started: 'Начать работу',
  },
  header: {
    planets: 'планеты',
    characters: 'персонажи',
    starships: 'звездолеты',
    films: 'фильмы',
  },
  planet: {
    population: 'Население',
    rotation_period: 'Период вращения',
    orbital_period: 'Орбитальный период',
    diameter: 'Диаметр',
    gravity: 'Гравитация',
    terrain: 'Земля',
    surface_water: 'Поверхностные воды',
    climate: 'Климат',
  },
  character: {
    birth_year: 'Год рождения',
    height: 'Рост',
    mass: 'Вес',
    gender: 'Пол',
    hair_color: 'Цвет волос',
    skin_color: 'Цвет кожи',
    homeworld: 'Родной мир',
    species: 'Вид',
  },
  starship: {
    model: 'Модель',
    manufacturer: 'Производитель',
    class: 'Класс',
    cost: 'Стоимость',
    speed: 'Скорость',
    hyperdrive_rating: 'Рейтинг гипердвигателя',
    MGLT: 'MGLT',
    length: 'Длина',
    cargo_capacity: 'Грузоподьёмность',
    minimum_сrew: 'Минимальный экипаж',
    passengers: 'Пассажиры',
  },
  film: {
    date_created: 'Дата выхода',
    director: 'Режиссёр',
    producer: 'Продюссер(ы)',
    opening_crawl: 'Вступительно слово',
  },
  auth: {
    sign_up: 'Регистрация',
    log_in: 'Вход',
    email: 'Электронный адрес',
    password: 'Пароль',
  },
}
